# Generated by Django 3.1 on 2020-12-15 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, verbose_name="Code")),
                ("value", models.FloatField(max_length=20, verbose_name="Value")),
                ("date", models.DateField(auto_now_add=True)),
                ("cashback_percent", models.IntegerField(verbose_name="% cashback")),
                ("cashback_value", models.FloatField(verbose_name="Value")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("V", "Em Validação"),
                            ("A", "Aprovado"),
                            ("N", "Negado"),
                        ],
                        default="V",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Sales",
            },
        ),
    ]
